### ISSUE TITLE
u-boot-2024 branch has been renamed

### ISSUE THREAD

**Issue by acostach** [compulab-yokneam/u-boot-compulab#6]
Hi @vraevsky ,

I see the branch named 'u-boot-compulab_v2022.04' has been renamed to 'to-be-removed/u-boot-compulab_v2022.04' , and the new branch no longer has the board configuration files for ucm-imx93. What is the plan for the old branch, for how long will it stay around? Currently this is breaking our builds, which are based on kirkstone, so I'm wondering what branch should be used for ucm-imx93 with u-boot 2022.04 instead?

Thanks

**Comment by acostach** [comment]
@vraevsky @ilyacompulab ^

**Comment by vraevsky** [comment]
Sorry I'm ooo. 
Will reply as soon as I'm back.

**Comment by vraevsky** [comment]
Hi @acostach.

Please use this branch:
https://github.com/compulab-yokneam/u-boot-compulab/tree/u-boot-compulab_v2023.04

Regards,
Valentin.

**Comment by vraevsky** [comment]
Considered solved.

**Comment by vraevsky** [comment]
Considered solved.
